### ISSUE TITLE
uninitialized constant ActionView::FileSystemResolver (NameError) in rails 4.1.0

### ISSUE THREAD

**Issue by ifeins** [emilioforrer/haml_coffee_assets#128] opened 2014-04-09 15:11 UTC
Hi,

I've upgraded my application to rails 4.1 and I'm getting the following error:
```
/Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/haml_coffee_assets-1.16.0/lib/haml_coffee_assets/action_view/resolver.rb:9:in `<module:ActionView>': uninitialized constant ActionView::FileSystemResolver (NameError)
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/haml_coffee_assets-1.16.0/lib/haml_coffee_assets/action_view/resolver.rb:4:in `<module:HamlCoffeeAssets>'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/haml_coffee_assets-1.16.0/lib/haml_coffee_assets/action_view/resolver.rb:3:in `<top (required)>'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/haml_coffee_assets-1.16.0/lib/haml_coffee_assets/rails/engine.rb:3:in `require'
source 'https://rubygems.org'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/haml_coffee_assets-1.16.0/lib/haml_coffee_assets/rails/engine.rb:3:in `<top (required)>'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/haml_coffee_assets-1.16.0/lib/haml_coffee_assets.rb:18:in `require'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/haml_coffee_assets-1.16.0/lib/haml_coffee_assets.rb:18:in `<top (required)>'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.1/lib/bundler/runtime.rb:76:in `require'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.1/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.1/lib/bundler/runtime.rb:72:in `each'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.1/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.1/lib/bundler/runtime.rb:61:in `each'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.1/lib/bundler/runtime.rb:61:in `require'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/bundler-1.6.1/lib/bundler.rb:132:in `require'
	from /Users/ifeins/Development/lunchtime/config/application.rb:7:in `<top (required)>'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:79:in `require'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:79:in `block in server'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/ifeins/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>' 
```

I see that you solve this in master, and indeed when I changed my Gemfile to 
```
gem 'haml_coffee_assets', git: "https://github.com/netzpirat/haml_coffee_assets"
```

it solved the issue.

Can you push the latest revision to rubygems?

**Comment by fruwe** [comment] 2015-01-26 08:24
RIP

**Comment by nevinera** [comment] 2015-05-07 01:10
If anyone else ends up here chasing this error message, you can fix it in your application by making sure that some specific files get required - I added these two lines to the top of my `application.rb`:

```ruby
require "action_view"
require "action_view/template/resolver"
```

**Comment by thomasstephane** [comment] 2015-07-23 16:57
Thanks @nevinera , this worked for me.

**Comment by jasonfb** [comment] 2016-01-26 12:00
I have come here following an urgent issue related to the rails security patch for 4.1.14.1

I am sorry to hear about @netzpirat (Mr. Michael Kessler of Switzerland)

The issue is fixed on my fork here https://github.com/mackweldon/haml_coffee_assets, although I realize with an inactive github account there will be noone to merge the PR in. I believe Github has an official repo abandonment process, I'm not sure if it covers the actual death of the account holder. I will email them to follow up

**Comment by jeremywadsack** [comment] 2016-02-04 23:51
It looks like @thedeeno, @fixme, and @zhrivodkin have all merged PRs. Do any of you have access to do that still?

I think the critical issue isn't GitHub but rubygems. Of course someone who wants to take over the gem can fork and rename it.

**Closed** 2016-05-12 16:13 UTC
